class MedicationTimingRule {
  const MedicationTimingRule({
    this.anchor = 'any',
    this.instructionAr = '',
    this.requiresMealChoice = false,
    this.autoScheduleSafe = true,
    this.source = '',
  });

  final String anchor;
  final String instructionAr;
  final bool requiresMealChoice;
  final bool autoScheduleSafe;
  final String source;
}

const medicationTimingRules = <String, MedicationTimingRule>{
  'levothyroxine': MedicationTimingRule(
    anchor: 'before-breakfast',
    instructionAr:
        'على معدة فارغة قبل الفطور بـ30–60 دقيقة. افصل الحديد والكالسيوم 4 ساعات على الأقل.',
    source: 'MedlinePlus Levothyroxine',
  ),
  'glimepiride': MedicationTimingRule(
    anchor: 'breakfast',
    instructionAr: 'مع الفطور أو أول وجبة رئيسية في اليوم.',
    source: 'MedlinePlus Glimepiride',
  ),
  'metformin': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr:
        'مع الوجبات. إذا كان المنتج ممتد المفعول مرة يوميًا فغالبًا مع وجبة المساء حسب الوصفة.',
    source: 'MedlinePlus Metformin',
  ),
  'tamsulosin': MedicationTimingRule(
    anchor: 'after-selected-meal',
    instructionAr: 'بعد نفس الوجبة كل يوم بـ30 دقيقة.',
    requiresMealChoice: true,
    source: 'MedlinePlus Tamsulosin',
  ),
  'rivaroxaban': MedicationTimingRule(
    anchor: 'any',
    instructionAr:
        'تعليمات الطعام تختلف حسب القوة والاستطباب؛ استخدم التوقيت المكتوب في الوصفة.',
    autoScheduleSafe: false,
    source: 'MedlinePlus Rivaroxaban',
  ),
  'fexofenadine': MedicationTimingRule(
    anchor: 'any',
    instructionAr:
        'مع الماء. تجنب عصير التفاح والبرتقال والجريب فروت وقت الجرعة.',
    source: 'MedlinePlus Fexofenadine',
  ),
  'bisacodyl-tablets': MedicationTimingRule(
    anchor: 'bedtime',
    instructionAr:
        'غالبًا مساءً. افصل ساعة على الأقل عن الحليب/الألبان ومضادات الحموضة.',
    source: 'MedlinePlus Bisacodyl',
  ),
  'nitrofurantoin': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'مع الطعام وفي مواعيد متباعدة حسب الوصفة.',
    source: 'MedlinePlus Nitrofurantoin',
  ),
  'valproic-acid': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'مع الطعام لتقليل انزعاج المعدة وفي أوقات ثابتة.',
    source: 'MedlinePlus Valproic Acid',
  ),
  'metoprolol': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr:
        'النوع العادي يؤخذ مع الوجبة أو بعدها مباشرة؛ اتبع نوع المنتج الموصوف.',
    source: 'MedlinePlus Metoprolol',
  ),
  'doxycycline': MedicationTimingRule(
    anchor: 'any',
    instructionAr:
        'مع كوب ماء كامل. يحتاج فصلًا عن بعض المعادن/مضادات الحموضة حسب المنتج.',
    source: 'MedlinePlus Doxycycline',
  ),
  'furosemide': MedicationTimingRule(
    anchor: 'morning',
    instructionAr:
        'يفضل تنظيم الجرعة مبكرًا بما يتوافق مع الوصفة لتقليل الاستيقاظ ليلًا للتبول.',
    source: 'Practical counseling rule',
  ),
  'hydrochlorothiazide': MedicationTimingRule(
    anchor: 'morning',
    instructionAr:
        'يفضل تنظيم الجرعة مبكرًا بما يتوافق مع الوصفة لتقليل التبول ليلًا.',
    source: 'Practical counseling rule',
  ),
  'empagliflozin': MedicationTimingRule(
    anchor: 'morning',
    instructionAr: 'مرة يوميًا صباحًا تقريبًا، مع الطعام أو بدونه.',
    source: 'MedlinePlus Empagliflozin',
  ),
  'semaglutide-injection': MedicationTimingRule(
    anchor: 'weekly',
    instructionAr: 'مرة أسبوعيًا في نفس اليوم من كل أسبوع.',
    source: 'MedlinePlus Semaglutide',
  ),
  'methotrexate-rheumatology': MedicationTimingRule(
    anchor: 'weekly',
    instructionAr:
        'للروماتيزم/الالتهاب: يوم واحد محدد في الأسبوع حسب الوصفة، وليس يوميًا.',
    source: 'DailyMed / MedlinePlus Methotrexate',
  ),
  'carvedilol': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'النوع العادي يؤخذ مع الطعام لتقليل هبوط الضغط والدوخة.',
    source: 'DailyMed Carvedilol',
  ),
  'sacubitril-valsartan': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو بدونه. الأهم الالتزام بالمرات المكتوبة وعدم جمعه مع ACE inhibitor.',
    source: 'FDA / DailyMed Sacubitril-Valsartan',
  ),
  'digoxin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في وقت ثابت يوميًا مع الطعام أو بدونه؛ ثبّت الطريقة قدر الإمكان.',
    source: 'DailyMed Digoxin',
  ),
  'amiodarone-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'خذ الجرعة بطريقة ثابتة بالنسبة للطعام كل يوم لتقليل تغير الامتصاص.',
    source: 'DailyMed Amiodarone',
  ),
  'diltiazem-er': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'تعليمات الطعام تختلف حسب منتج ER؛ اختر توقيت الوصفة ولا تعتمد Auto.',
    autoScheduleSafe: false,
    source: 'Product-specific DailyMed Diltiazem ER',
  ),
  'dapagliflozin': MedicationTimingRule(
    anchor: 'morning',
    instructionAr: 'مرة يوميًا ويمكن مع الطعام أو بدونه؛ تنظيمها صباحًا يقلل نسيان الجرعة لدى كثير من المرضى.',
    source: 'FDA / DailyMed Dapagliflozin',
  ),
  'insulin-lispro': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'إنسولين وجبات؛ اختر الوجبة/الأوقات حسب الوصفة ولا تستخدم Auto إذا لم تكن علاقة الجرعة بالطعام محددة.',
    requiresMealChoice: true,
    autoScheduleSafe: false,
    source: 'FDA product IFU Insulin Lispro',
  ),
  'prednisone': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'التوقيت والوجبات وعدد الجرعات يعتمد على الخطة؛ لا ينشئ التطبيق جدولًا تلقائيًا دون مراجعة الوصفة.',
    autoScheduleSafe: false,
    source: 'DailyMed / MedlinePlus Prednisone',
  ),
  'methimazole': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'خذ الجرعات في أوقات ثابتة ويمكن مع الطعام أو بدونه؛ ثبّت الطريقة إذا أزعج المعدة.',
    source: 'DailyMed Methimazole',
  ),
  'ciprofloxacin-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يحتاج فصلًا عن مضادات الحموضة والحديد والزنك والكالسيوم حسب ملصق المنتج.',
    source: 'FDA Medication Guide Ciprofloxacin',
  ),
  'carbamazepine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات ثابتة حسب النوع العادي أو الممتد؛ لا تغيّر formulation دون مراجعة.',
    source: 'FDA Medication Guide Carbamazepine',
  ),
  'lamotrigine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في وقت ثابت ويمكن مع الطعام أو بدونه؛ لا تعاود الجرعة القديمة تلقائيًا بعد انقطاع عدة أيام.',
    source: 'DailyMed Medication Guide Lamotrigine',
  ),
  'pregabalin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'تعليمات IR وER تختلف؛ اختر توقيت الوصفة إذا كان المنتج ممتد المفعول.',
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Pregabalin',
  ),
  'pantoprazole': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'الحبوب المتأخرة التحرر تختلف عن الحبيبات في تعليمات الطعام؛ اتبع نوع المنتج.',
    autoScheduleSafe: false,
    source: 'DailyMed Pantoprazole',
  ),
  'metoclopramide': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'غالبًا يرتبط بالوجبات حسب الاستطباب؛ استخدم توقيت الوصفة بدل Auto.',
    autoScheduleSafe: false,
    source: 'DailyMed Metoclopramide',
  ),
  'sucralfate': MedicationTimingRule(
    anchor: 'empty-stomach',
    instructionAr: 'على معدة فارغة، مع فصل الأدوية المتداخلة حسب كل دواء.',
    source: 'DailyMed Sucralfate',
  ),
  'pancrelipase': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'أثناء الوجبة أو السناك؛ لا يُؤخذ بعيدًا عن الطعام.',
    source: 'FDA / DailyMed Pancrelipase IFU',
  ),
  'allopurinol': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'يمكن بعد الطعام لتقليل انزعاج المعدة؛ استمر يوميًا حسب خطة خفض اليوريك.',
    source: 'DailyMed Allopurinol',
  ),
  'hydroxychloroquine': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'مع الطعام أو الحليب لتقليل انزعاج المعدة.',
    source: 'DailyMed Hydroxychloroquine',
  ),
  'dabigatran': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات ثابتة؛ ابتلع الكبسولة كاملة ولا تفتحها أو تمضغها.',
    source: 'FDA Medication Guide Dabigatran',
  ),
  'mirabegron': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في وقت ثابت يوميًا؛ ابتلع الحبة ممتدة المفعول كاملة.',
    source: 'DailyMed Mirabegron',
  ),
  'alendronate': MedicationTimingRule(
    anchor: 'before-breakfast',
    instructionAr: 'عند الاستيقاظ مع ماء عادي فقط، قبل الطعام/الدواء 30 دقيقة على الأقل، والبقاء جالسًا أو واقفًا.',
    source: 'FDA / DailyMed Alendronate',
  ),
  'sildenafil-ed': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'دواء عند الحاجة وليس له جدول يومي تلقائي؛ استخدمه حسب وصفة ضعف الانتصاب.',
    autoScheduleSafe: false,
    source: 'DailyMed Sildenafil ED',
  ),
  'losartan': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في وقت ثابت يوميًا؛ يمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed / MedlinePlus Losartan',
  ),
  'salbutamol-mdi': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'غالبًا بخاخ إسعاف عند الحاجة. إذا كانت الوصفة بجرعات ثابتة فاختر توقيتها يدويًا ولا تعتمد Auto.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / device IFU Albuterol HFA',
  ),
  'amoxicillin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو بدونه؛ ثبّت الفواصل حسب التكرار الموصوف وأكمل الكورس.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Amoxicillin',
  ),
  'levetiracetam': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات ثابتة ويمكن مع الطعام أو بدونه؛ انتبه لاختلاف IR وXR.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Levetiracetam',
  ),
  'omeprazole': MedicationTimingRule(
    anchor: 'before-meal',
    instructionAr: 'غالبًا قبل الوجبة؛ كثير من الأنظمة تؤخذ 30–60 دقيقة قبل الطعام. إذا كانت الوصفة أكثر من مرة أو formulation مختلفًا اختر التوقيت المكتوب في الوصفة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Omeprazole',
  ),
  'paracetamol': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مع الطعام أو بدونه، حسب الحاجة/التكرار الموصوف مع مراعاة الحد اليومي من جميع المنتجات.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Acetaminophen',
  ),
  'apixaban': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات ثابتة ويمكن مع الطعام أو بدونه؛ لا توقفه أو تغيّر توقيته قبل إجراء دون خطة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA / DailyMed Apixaban',
  ),
  'cetirizine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو بدونه. إذا سبب نعاسًا يمكن مناقشة تنظيمه مساءً.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Cetirizine',
  ),
  'amlodipine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا غالبًا وفي وقت ثابت؛ يمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Amlodipine',
  ),
  'lisinopril': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في وقت ثابت يوميًا؛ يمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Lisinopril',
  ),
  'insulin-glargine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'إنسولين قاعدي: اربطه بالوقت الذي وصفه الطبيب لنفس المنتج. لا ينشئ التطبيق وقتًا تلقائيًا عند اختلاف الخطة/المنتج.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA product IFU Insulin Glargine',
  ),
  'budesonide-formoterol': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'جرعات الصيانة في أوقات ثابتة حسب الوصفة. استخدامه كمسكن/MART يعتمد على المنتج والخطة ولا يُفترض تلقائيًا.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / product IFU Budesonide-Formoterol',
  ),
  'montelukast': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'التوقيت يعتمد على الاستطباب؛ للربو كثيرًا ما تكون الجرعة مساءً، بينما تعليمات الحساسية/الجهد تختلف. اختر توقيت الوصفة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Montelukast',
  ),
  'ibuprofen': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو الحليب إذا أزعج المعدة؛ استخدم أقل مدة/جرعة مناسبة ولا تجمع NSAID آخر.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Ibuprofen',
  ),
  'warfarin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا في وقت ثابت. المهم الثبات والمتابعة مع INR؛ لا تغيّر الجرعات حسب الجدول من نفسك.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Warfarin',
  ),
  'upadacitinib': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا مع الطعام أو بدونه؛ ابتلع ER كاملة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA / DailyMed Upadacitinib',
  ),
  'tofacitinib': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR وXR لهما جداول مختلفة؛ إذا كان الشكل غير محدد اختر التوقيت يدويًا بدل Auto.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Tofacitinib',
  ),
  'dupilumab': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'حقنة حسب الجدول الخاص بالاستطباب/العمر؛ إذا لم تكن الجرعة أسبوعية فلا يحول التطبيق التكرار من نفسه.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DUPIXENT IFU',
  ),
  'polyethylene-glycol-3350': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن في وقت يناسب المريض بعد إذابة الجرعة بالكامل؛ ليس مرتبطًا بوجبة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed PEG 3350',
  ),
  'lactulose': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات ثابتة حسب الوصفة؛ يمكن مع الطعام أو بدونه. في الاعتلال الدماغي يُعدّل حسب هدف البراز الطبي.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Lactulose',
  ),
  'loperamide': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'غالبًا عند الحاجة ضمن الحد المسموح وليس له وقت ثابت؛ إذا وُصف بجدول خاص فاتبع الوصفة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Loperamide',
  ),
  'ondansetron-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'التوقيت يعتمد على سبب الاستخدام (غثيان/علاج كيماوي/عملية)؛ اختر توقيت الوصفة إذا كان محددًا.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Ondansetron',
  ),
  'levonorgestrel-ec': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'خذها بأسرع ما يمكن ضمن نافذة المنتج بعد الجماع غير المحمي؛ ليست جرعة يومية مجدولة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA emergency contraception labeling',
  ),
  'latanoprost': MedicationTimingRule(
    anchor: 'bedtime',
    instructionAr: 'عادة نقطة مرة يوميًا مساءً؛ لا تستخدم أكثر من مرة يوميًا.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Latanoprost',
  ),
  'paracetamol-pediatric-liquid': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'حسب الحاجة والفاصل الموصوف وبالتركيز الصحيح؛ لا ينشئ التطبيق جرعة طفل.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Pediatric Acetaminophen',
  ),
  'atorvastatin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا في وقت ثابت؛ يمكن مع الطعام أو بدونه وفي أي وقت من اليوم.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Atorvastatin',
  ),
  'spironolactone': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'خذها بطريقة ثابتة بالنسبة للطعام لأن الطعام قد يغيّر الامتصاص؛ التزم بنفس الروتين يوميًا.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Spironolactone',
  ),
  'sertraline': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا غالبًا؛ مع الطعام أو بدونه وفي وقت ثابت يناسب النوم/التحمل.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Sertraline',
  ),
  'gabapentin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR وER/prodrug ليست نفس الجدول أو تعليمات الطعام؛ إذا لم يتحدد formulation اختر توقيت الوصفة يدويًا.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Gabapentin',
  ),
  'clindamycin-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات متباعدة حسب الوصفة، مع كوب ماء كامل؛ الطعام اختياري.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Clindamycin',
  ),
  'clopidogrel': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا في وقت ثابت؛ يمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Clopidogrel',
  ),
  'nitroglycerin-sublingual': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'دواء إسعافي عند ألم الذبحة وليس له وقت ثابت؛ استخدم خطة الألم الموصوفة واطلب المساعدة عند استمرار الألم.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Nitroglycerin SL',
  ),
  'sitagliptin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Sitagliptin',
  ),
  'tiotropium-capsule-inhalation': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا غالبًا وفي نفس الوقت؛ الكبسولة للاستنشاق فقط وليست للبلع.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA HandiHaler IFU',
  ),
  'azithromycin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR يمكن عادة مع الطعام أو بدونه؛ extended-release suspension لها تعليمات معدة فارغة. إذا لم يتحدد المنتج لا تستخدم Auto.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Azithromycin',
  ),
  'acyclovir-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'في أوقات متباعدة حسب الوصفة مع ترطيب مناسب إن لم يوجد تقييد سوائل؛ الطعام اختياري.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Acyclovir',
  ),
  'metronidazole-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR وER تختلف في علاقتها بالطعام؛ إذا كان الشكل غير محدد اختر توقيت الوصفة يدويًا.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Metronidazole',
  ),
  'combined-oral-contraceptive': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'حبة يوميًا في وقت ثابت واتبع ترتيب العبوة بالضبط؛ قواعد الحبوب المنسية تعتمد على المنتج.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'CDC SPR + product labeling',
  ),
  'norethindrone-pop': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'نفس الوقت كل يوم مهم جدًا؛ norethindrone POP لها نافذة تأخر أضيق من بعض POP الأخرى.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'CDC SPR + norethindrone labeling',
  ),
  'finasteride': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا في وقت ثابت؛ مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Finasteride',
  ),
  'timolol-ophthalmic': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'قطرة حسب عدد المرات الموصوف؛ ثبّت الأوقات واستخدم ضغط القناة الدمعية لتقليل الامتصاص الجهازي.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Timolol Ophthalmic',
  ),
  'ciprofloxacin-ophthalmic': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'وزّع القطرات حسب التكرار الموصوف؛ جداول drops وointment تختلف ولا تُفترض تلقائيًا.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Ciprofloxacin Ophthalmic',
  ),
  'ciprofloxacin-otic': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'استخدم القطرات في أوقات ثابتة حسب المنتج؛ single-agent وcombination ليست نفس التعليمات.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Ciprofloxacin Otic',
  ),
  'naproxen': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'حسب التكرار الموصوف؛ يمكن مع الطعام إذا أزعج المعدة ولا تجمع NSAID آخر.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Naproxen',
  ),
  'senna': MedicationTimingRule(
    anchor: 'bedtime',
    instructionAr: 'غالبًا مساءً/قبل النوم لأن المفعول يحتاج عدة ساعات؛ لا تكرر جرعات إضافية بسرعة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Senna',
  ),
  'hydrocortisone-topical': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'ضع طبقة رقيقة حسب عدد المرات المكتوب؛ لا يحدد التطبيق أوقاتًا صارمة للدهان الموضعي.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Hydrocortisone Topical',
  ),
  'ipratropium-hfa': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'قد يكون مجدولًا أو حسب الحاجة وفق COPD/الخطة؛ إذا لم يكن النظام واضحًا اختر توقيت الوصفة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA Atrovent HFA IFU',
  ),
  'fluticasone-hfa': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'بخاخ وقائي في أوقات ثابتة حسب الوصفة؛ ليس مرتبطًا بالطعام.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA Fluticasone inhaler IFU',
  ),
  'fluticasone-salmeterol-dpi': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'بخاخ وقائي في أوقات ثابتة حسب الوصفة؛ لا يُستخدم كنفس طريقة بخاخ الإسعاف.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA Fluticasone/Salmeterol DPI IFU',
  ),
  'fluconazole-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو بدونه؛ عدد الجرعات والمدة يختلفان كثيرًا حسب نوع العدوى.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Fluconazole',
  ),
  'cefuroxime-axetil': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'تعليمات الطعام تختلف حسب الشكل؛ كثير من الأقراص تُعطى بعد الطعام لتحسين الامتصاص. تحقق من منتجك.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Cefuroxime Axetil',
  ),
  'fluoxetine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا غالبًا وفي وقت ثابت؛ يمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Fluoxetine',
  ),
  'escitalopram': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا وفي وقت ثابت؛ مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Escitalopram',
  ),
  'duloxetine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا أو حسب الوصفة؛ يمكن غالبًا مع الطعام أو بدونه، وابتلع delayed-release حسب المنتج.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Duloxetine',
  ),
  'amitriptyline': MedicationTimingRule(
    anchor: 'bedtime',
    instructionAr: 'إذا كانت جرعة واحدة يوميًا فغالبًا تنظم ليلًا بسبب النعاس؛ اتبع الوصفة إذا كانت الجرعات مقسمة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Amitriptyline',
  ),
  'quetiapine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR وXR تختلف في التوقيت والطعام؛ اختر توقيت الوصفة ولا تعتمد Auto إذا لم يتحدد المنتج.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Quetiapine',
  ),
  'famotidine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'التوقيت يعتمد على الاستطباب ويمكن مع الطعام أو بدونه؛ جرعات الوقاية من الحموضة قد ترتبط بوجبة محفزة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Famotidine',
  ),
  'celecoxib': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'التوقيت والطعام يعتمدان على الجرعة/المنتج؛ استخدم الجدول الموصوف ولا تجمع NSAID آخر.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Celecoxib',
  ),
  'diclofenac-oral': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'IR/DR/ER ليست نفس التوقيت أو التعامل؛ اختر توقيت الوصفة ولا تعتمد Auto دون معرفة المنتج.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA / DailyMed Diclofenac',
  ),
  'colchicine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'جدول النوبة والوقاية مختلفان؛ استخدم النظام الموصوف ولا يحول التطبيق بينهما.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'DailyMed Colchicine',
  ),
  'enoxaparin': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'حقن تحت الجلد في أوقات ثابتة حسب q24h/q12h الموصوف؛ الطعام غير مهم.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA Enoxaparin IFU',
  ),
  'loratadine': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'مرة يوميًا غالبًا ويمكن مع الطعام أو بدونه.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'DailyMed Loratadine',
  ),
  'tacrolimus-topical': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'ضع طبقة رقيقة حسب عدد المرات الموصوف؛ لا تربطه بوجبة.',
    requiresMealChoice: false,
    autoScheduleSafe: true,
    source: 'FDA Tacrolimus Ointment',
  ),
  'adalimumab': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'الجدول يختلف حسب الاستطباب والمنتج (أسبوعي/كل أسبوعين/تحميل). لا تعتمد Auto إلا إذا أدخلت تكرار الوصفة بدقة.',
    requiresMealChoice: false,
    autoScheduleSafe: false,
    source: 'FDA Adalimumab IFU',
  ),
  'oral-iron-salts': MedicationTimingRule(
    anchor: 'empty-stomach',
    instructionAr:
        'الأفضل على معدة فارغة. افصل عن الحليب/الكالسيوم/مضادات الحموضة ساعتين على الأقل.',
    source: 'NIH ODS / MedlinePlus Iron',
  ),
  'calcium-carbonate': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'مع وجبة.',
    source: 'NIH ODS Calcium',
  ),
  'calcium-citrate': MedicationTimingRule(
    anchor: 'any',
    instructionAr: 'يمكن مع الطعام أو بدونه.',
    source: 'NIH ODS Calcium',
  ),
  'magnesium-gluconate': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr: 'مع الوجبات لتقليل انزعاج المعدة.',
    source: 'MedlinePlus Magnesium Gluconate',
  ),
  'vitamin-d3': MedicationTimingRule(
    anchor: 'with-meal',
    instructionAr:
        'مع وجبة أو سناك يحتوي بعض الدهون لتحسين الامتصاص.',
    source: 'NIH ODS Vitamin D',
  ),
  'zinc': MedicationTimingRule(
    anchor: 'any',
    instructionAr:
        'إذا استُخدم مع tetracycline/quinolone antibiotic يحتاج فصلًا زمنيًا.',
    source: 'NIH ODS Zinc',
  ),
};
